theater/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('theater_operas.urls', namespace='theater_operas')),
        
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

theater_operas/urls.py
from django.urls import path
from .views import works_list, works_detail, part_detail, text_detail

app_name = 'theater_operas'

urlpatterns = [
  path('', works_list, name='works_list'),
  path('<slug>/', works_detail, name='works_detail'),
  path('<work_slug>/<int:part_number>', part_detail, name='part-detail'),
  path('<work_slug>/<part_number>/<text_number>/', text_detail, name='text_detail'),
]

theater_operas/models.py
from django.db import models
from django.shortcuts import redirect, reverse

# Maestro 
#     Opera
#       Part     
#         Text       
#           Mention1            
#           Mention2           
  
  
class Maestro(models.Model):
  complete_name = models.CharField(max_length=50)
  country_maestro = models.CharField(max_length=50)
  slug = models.SlugField()
  
  def __str__(self):
    return f"{self.complete_name} {self.country_maestro}"
  
class Work(models.Model):
  maestros = models.ManyToManyField(Maestro)
  title = models.CharField(max_length=50)
  publication_date = models.DateTimeField()
  gendre = models.CharField(max_length=30)
  slug = models.SlugField()
  cover = models.ImageField()
  price = models.FloatField()
  
  def __str__(self):
    return self.title
  
  def get_absolute_url(self):
    return reverse("theater_operas:works_detail", kwargs={'slug': self.slug })
  
class Part(models.Model):
  work = models.ForeignKey(Work, on_delete=models.CASCADE)
  part_number = models.IntegerField()
  title = models.CharField(max_length=50)
  
  def __str__(self):
    return self.title
  
  def get_absolute_url(self):
    return reverse("theater_operas:part-detail", kwargs={'work_slug': self.work.slug, 'part_number': self.part_number }) 

class Text(models.Model):
  part = models.ForeignKey(Part, on_delete=models.CASCADE)
  text_number = models.IntegerField()
  text_page_number = models.IntegerField()
  title = models.CharField(max_length=50)
  
  def __str__(self):
    return self.title
  
  def get_absolute_url(self):
    return reverse("theater_operas:text_detail", kwargs={'work_slug': self.part.work.slug, 'part_number': self.part.part_number, 'text_number': self.text_number })
class Mention(models.Model):
  text = models.ForeignKey(Text, on_delete = models.CASCADE)
  image = models.ImageField()
  
  def __str__(self):
    return f"{self.text.title}-{self.pk}"   
            

theater_operas/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404

from .models import Work, Part, Text

def works_list(request):
  # display all of the theater_work
  queryset = Work.objects.all()         
  context = {
    'queryset': queryset
  }
  return render(request, "works_list.html", context)

def works_detail(request, slug):
  # display some details of the work presented
  work = get_object_or_404(Work, slug=slug)
  context = {
    'work': work
  }
  return render(request, "work_detail.html", context)

def part_detail(request, work_slug, part_number):
  part_qs = Part.objects \
    .filter(work__slug=work_slug) \
    .filter(part_number=part_number)
  if part_qs.exists():
    context = {
      'part': part_qs[0] 
    }
    return render(request, "part_detail.html", context)
  return Http404

def text_detail(request, work_slug, part_number, text_number):
  text_qs = Text.objects \
    .filter(part__work__slug=work_slug) \
    .filter(part__part_number=part_number) \
    .filter(text_number = text_number)
  if text_qs.exists():
    context = {
      'text': text_qs[0] 
    }
    return render(request, "text_detail.html", context)
  return Http404    
  
  
        

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Theater Works</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>
<body>
<div class="container"> 
  <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    {% block breadcrumb %}
    
    {% endblock breadcrumb %}
  </ol>
  </nav>
  
  {% block content %}

  {% endblock %}
  </div>


    
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/part_detail.html
{% extends "base.html" %}

{% block breadcrumb %}
    <li class="breadcrumb-item " aria-current="page">
      <a href="{% url 'theater_operas:works_list' %}">Works list</a>
    </li>
    <li class="breadcrumb-item " aria-current="page">
      <a href="{{ part.work.get_absolute_url }}">{{ part.work.title }}</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
    {{ part }}
    </li>
{% endblock breadcrumb %}

{% block content %}
<div class="row">
  <main class="col-md-4">
    <div class="card" style="width: 18rem;">
      <div class="card-header">{{ part.work.title }}</div>
      <img src="..{{ part.work.cover.url }}." class="card-img-top" alt="...">
      <div class="card-body">
        <p class="card-text">Published{{ part.work.publication_date }}</p>
      </div>
    </div>

  </main>

  <aside class="col-md-8">
    <div class="card">
        <div class="card-header">
          Detail of a specific part of a work
        </div>
        <ul class="list-group list-group-flush">
          {% for text in part.text_set.all %}
            <li class="list-group-item">
              <a href="{{ text.get_absolute_url }}">
                {{ text.text_number }}. {{ text.title }}
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>  
    </aside>
  </div>
{% endblock content %}

templates/text_detail.html
{% extends "base.html" %}

{% block breadcrumb %}
    <li class="breadcrumb-item " aria-current="page">
      <a href="{% url 'theater_operas:works_list' %}">Works list</a>
    </li>
    <li class="breadcrumb-item " aria-current="page">
      <a href="{{ text.part.work.get_absolute_url }}">{{ text.part.work.title }}</a>
    </li>
    <li class="breadcrumb-item" aria-current="page">
    <a href="{{ text.part.get_absolute_url }}">{{ text.part.title }}</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
    {{ text.title }}
    </li>
{% endblock breadcrumb %}

{% block content %}
  <div class="row">
    <main class="col-md-4">
      <div class="card" style="width: 18rem;">
        <div class="card-header">{{ text.part.work.title }}</div>
        <img src="..{{ text.part.work.cover.url }}." class="text.card-img-top" alt="...">
        <div class="card-body">
          <p class="card-text">Published{{ part.work.publication_date }}</p>
        </div>
      </div>
    </main>
  <aside class="col-md-8">
    <div class="card">
        <div class="card-header">
          Mentions details
        </div>
        
        {% for mention in text.mention_set.all %}
            <div class="accordion" id="toggle-{{ mention.mention_number }}">
                <div class="card">
                    <div class="card-header" id="heading-{{ mention.mention_number }}">
                    <h2 class="mb-0">
                        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse-{{ mention.mention_number }}" aria-expanded="true" aria-controls="collapse-{{ mention.mention_number }}">
                        Solution {{ mention.mention_number }}
                        </button>
                    </h2>
                    </div>

                    <div id="collapse-{{ solution.solution_number }}" class="collapse" aria-labelledby="heading-{{ mention.mention_number }}" data-parent="#toggle-{{ mention.mention_number }}">
                    <div class="card-body">
                        <img src="{{ mention.image.url }}" class="card-img-top" alt="...">
                    </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        
          {% for mention in text.mention_set.all %}
            <li class="list-group-item">
              <a href="{{ text.get_absolute_url }}">
                Mentions {{ mention.mention_number }}
              </a>
            </li>
          {% endfor %}
        
      </div>  
    </aside>
  </div>    
{% endblock content %}

templates/work_detail.html
{% extends "base.html" %}

{% block breadcrumb %}
    <li class="breadcrumb-item " aria-current="page">
      <a href="{% url 'theater_operas:works_list' %}">Works list</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">{{work.title}}</li>
{% endblock breadcrumb %}

{% block content %}
<div class="row">
  <main class="col-md-4">
    <div class="card" style="width: 18rem;">
      <div class="card-header">{{ work.title }}</div>
      <img src="..{{ work.cover.url }}." class="card-img-top" alt="...">
      <div class="card-body">
        <p class="card-text">Published{{ work.publication_date }}</p>
      </div>
    </div>

  </main>

  <aside class="col-md-8">
    <div class="card">
        <div class="card-header">
          Parts of a work
        </div>
        <ul class="list-group list-group-flush">
          {% for part in work.part_set.all %}
            <li class="list-group-item"><a href="{{part.get_absolute_url}}">
              {{ part.part_number }}.  {{ part.title }}</a>
            </li>
          {% endfor %}
        </ul>
      </div>  
    </aside>
  {% endblock %}

templates/works_list.html
{% extends "base.html" %}

{% block breadcrumb %}
    <li class="breadcrumb-item active" aria-current="page">Works list</li>
{% endblock breadcrumb %}

{% block content %}
    
  <h1>This is the Theater Works list</h1>
  <hr />
  {% for work in queryset %}
  <div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{work.title}}</h5>
    <h6 class="card-subtitle mb-2 text-muted">{{work.publication_date}}</h6>
    <p class="card-text">
      {% for maestro in work.maestros.all %}
          <span>{{ maestro }}</span>
          {% if work.maestros.count > 1 %} | {% endif %} 
      {% endfor %}  
    </p>
    <a href="{{ work.get_absolute_url }}" class="card-link">{{ work }}</a>
  </div>
  </div>
  {% endfor %}

{% endblock %}


    